server:
 port: 8085

spring:
 h2:
    console:
      enabled: true
      path: /h2-console
 jpa:
    hibernate:
      ddl-auto: update
 application:
  name: department-service
  
 datasource:
  url: jdbc:h2:mem:testdb
  
      
