spring:
 h2:
    console:
      enabled: true
      path: /h2-console
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 application:
  name: employee-service
  
 datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  
      
